version: "3"

# volumes:
#   db:
#   logs:
name: vtb_backend
services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    # volumes:
    #   - "db:/var/lib/postgresql/data"
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    # volumes:
    #   - "logs:/data"
    ports:
      - "3333:3333"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend-algakz.loadbalancer.server.port=3333"
      - "traefik.http.routers.frontend-algakz.rule=Host(`algakz.itatmisis.ru`)"
      - "traefik.http.routers.frontend-algakz.entrypoints=websecure"
      - "traefik.http.routers.frontend-algakz.tls=true"


